server:
  port: 8080
  servlet:
    context-path: /bookmanager
spring:
  datasource:
    url: jdbc:mysql://101.33.214.27:3306/library-manager-system?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml #mapper-locations是用来注册你写的xxxmapper.xml文件
  type-aliases-package: com.example.bookmanager.entity